name: txn_monitoring
version: "1.0.0"
config-version: 2
profile: txn_monitoring

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  txn_monitoring:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
